services:
    WebInterface:
        environment:
            FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
            DEBUG_MODE: ${DEBUG_MODE}
        build:
            context: .
            dockerfile: ./Dockerfiles/Dockerfile.WebInterface
        image: web-interface
        volumes:
            - ./WebInterface:/WebInterface
        networks:
            - books_explorer_internal
            - books_explorer_external
        ports:
            - "5000:5000"
        command: python -m WebInterface

networks:
    books_explorer_internal:
        internal: true
    books_explorer_external: