services:
    Proxy:
        environment:
            DOMAIN_NAME: ${DOMAIN_NAME}
        build: 
            context: .
            dockerfile: ./Dockerfiles/Dockerfile.Proxy
        image: proxy-nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./Proxy/ssl/local_cert:/etc/letsencrypt/live/${DOMAIN_NAME}
            - ./Proxy/ssl:/etc/letsencrypt 
            - ./Certbot/www:/var/www/certbot
    
    Certbot:
        image: certbot/certbot
        volumes:
            - ./Proxy/ssl:/etc/letsencrypt
            - ./Certbot/www:/var/www/certbot
        depends_on:
            - Proxy
        command: certonly --webroot --webroot-path=/var/www/certbot --email ${EMAIL_ID} --agree-tos -d ${DOMAIN_NAME}