services:
    Proxy:
        container_name: nginx_proxy 
        environment:
            DOMAIN_NAME: ${DOMAIN_NAME}
        build: 
            context: .
            dockerfile: ./Dockerfiles/Dockerfile.Proxy
            args:
                UID: ${UID}
                GID: ${GID}
        image: proxy-nginx
        networks:
            - books_explorer_external
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./Proxy/ssl/local_cert:/etc/letsencrypt/live/${DOMAIN_NAME}
            - ./Proxy/ssl:/etc/letsencrypt:ro
            - ./Certbot/www:/var/www/certbot:rw
    
    Certbot:
        container_name: certbot
        user: "${UID}:${GID}"
        image: certbot/certbot
        volumes:
            - ./Proxy/ssl:/etc/letsencrypt:rw
            - ./Certbot/www:/var/www/certbot:rw
        networks:
            - books_explorer_external
        depends_on:
            - Proxy
        command: certonly --webroot --webroot-path=/var/www/certbot --email ${EMAIL_ID} --agree-tos -d ${DOMAIN_NAME}

networks:
    books_explorer_external: