services:
    BooksDatabase:
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        image: mongo:7.0
        ports:
            - "27017:27017"
        healthcheck:
            test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
            interval: 2s
            timeout: 2s
            retries: 10

    DataExtraction:
        environment:
            AMOUNT_BOOKS: ${AMOUNT_BOOKS}
            MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@BooksDatabase:27017/"
            DB_NAME: ${DB_NAME}
        build:
            context: .
            dockerfile: Dockerfile_DataExtraction
        image: data-extraction
        depends_on:
            BooksDatabase:
                condition: service_healthy
        command: sh -c "python -m DataProcessing.DataInsertion.InsertBooks && python -m DataProcessing.DataPreprocessing.InsertSimilarities"

    RecommenderSystem:
        environment:
            MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@BooksDatabase:27017/"
            DB_NAME: ${DB_NAME}
        build:
            context: .
            dockerfile: Dockerfile_RecommenderSystem
        image: recommend-system
        volumes:
            - ./RecommenderSystem:/RecommenderSystem
        ports:
            - "8013:8013"
        depends_on:
            BooksDatabase:
                condition: service_healthy
            DataExtraction:
                condition: service_completed_successfully
        command: sh -c "sleep 15 && python app.py"