FROM python:3.12.5-slim-bookworm

WORKDIR /app

COPY --chmod=700 requirements_DataExtraction.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements_DataExtraction.txt

COPY --chmod=700 ./DataProcessing ./DataProcessing