FROM python:3.12.5-alpine

WORKDIR /Website

COPY --chmod=700 requirements_frontend.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements_frontend.txt

CMD ["python","app.py"]