services:
    BooksDatabase:
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        image: mongo:7.0
        ports:
            - "27017:27017"
        healthcheck:
            test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
            interval: 2s
            timeout: 2s
            retries: 10

    DataExtraction:
        environment:
            AMOUNT_BOOKS: ${AMOUNT_BOOKS}
            MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@BooksDatabase:27017/"
            DB_NAME: ${DB_NAME}
        build:
            context: .
            dockerfile: Dockerfile_DataExtraction
        image: backend:0.2
        depends_on:
            BooksDatabase:
                condition: service_healthy
        command: python -m DataProcessing.DataInsertion.InsertBooks

    WebInterface:
        environment:
            FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
            DEBUG_MODE: ${DEBUG_MODE}
            MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@BooksDatabase:27017/"
            DB_NAME: ${DB_NAME}
        build:
            context: .
            dockerfile: Dockerfile_WebInterface
        image: frontend:0.2
        volumes:
            - ./Website:/Website
        ports:
            - "5000:5000"
        depends_on:
            - DataExtraction