FROM python:3.12.5-slim-bookworm

ARG UID
ARG GID

RUN groupadd -r --gid ${GID} groups
RUN useradd -r --uid ${UID} --gid ${GID} user

COPY --chmod=750 ./DataExtraction ./DataExtraction
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r /DataExtraction/requirements_DataExtraction.txt

RUN chown -R ${UID}:${GID} ./DataExtraction

USER ${UID}

RUN chmod -R 700 ./DataExtraction