FROM nginx:1.27.4

ARG UID
ARG GID

RUN groupadd -r --gid ${GID} groups
RUN useradd -r --uid ${UID} --gid ${GID} user

RUN apt-get update && apt-get install -y gosu 

COPY --chmod=600 ./Proxy/conf.d/nginx.conf /etc/nginx/conf.d/nginx.conf.template
COPY --chmod=500 ./Proxy/conf.d/BuildConf.sh /etc/nginx/conf.d/BuildConf.sh

CMD /etc/nginx/conf.d/BuildConf.sh