FROM mongo:7.0

ARG UID
ARG GID

RUN groupadd -r --gid ${GID} groups
RUN useradd -r --uid ${UID} --gid ${GID} user

RUN chown -R ${UID}:${GID} /data/db /docker-entrypoint-initdb.d

USER ${UID}

CMD ["mongod"]